### PR TITLE
base-files: Fix config_generate when there are no switch VLANs or ports configured in board.json

### PR DESCRIPTION
**Pull request by VittGam**
The json_select call fails when there are no roles or ports objects in board.json. "json_select .." must not be executed after failing.

This fixes for example LEDs not being set up in /etc/config/system.

This is v2 of the patch using `json_is_a` as suggested by @jow- .

Cheers,
Vittorio

### CODE REVIEW

**Comment by jow-** [comment]
@VittGam - I believe it should be `json_is_a ... array` in both cases, at least my board.json looks like this:

    {
    	"model": {
    		"id": "tl-wdr4900-v1",
    		"name": "TP-Link TL-WDR4900 v1"
    	},
    	"switch": {
    		"switch0": {
    			"enable": true,
    			"reset": true,
    			"ports": [
    				{
    					"num": 0,
    					"device": "eth0",
    					"need_tag": false
    				},
    				{
    					"num": 2,
    					"role": "lan",
    					"index": 1
    				},
    				{
    					"num": 3,
    					"role": "lan",
    					"index": 2
    				},
    				{
    					"num": 4,
    					"role": "lan",
    					"index": 3
    				},
    				{
    					"num": 5,
    					"role": "lan",
    					"index": 4
    				},
    				{
    					"num": 1,
    					"role": "wan"
    				}
    			],
    			"roles": [
    				{
    					"role": "lan",
    					"ports": "2 3 4 5 0t",
    					"device": "eth0.1"
    				},
    				{
    					"role": "wan",
    					"ports": "1 0t",
    					"device": "eth0.2"
    				}
    			]
    		}
    	},
    	"network": {
    		"lan": {
    			"ifname": "eth0.1",
    			"protocol": "static"
    		},
    		"wan": {
    			"ifname": "eth0.2",
    			"protocol": "dhcp",
    			"macaddr": "a0:f3:c1:f8:5b:25"
    		}
    	}
    }

So `ports` and `roles` do refer to array, not objects.

**Comment by VittGam** [comment]
I'm not sure I follow the logic of `generate_switch_vlans_ports` then. I'm waiting for exactly a WDR4900v1 to be delivered to me soon, so I will be able to check this on the real hardware.

**Comment by VittGam** [comment]
Okay, I've got the hardware and compiled Lede for it.

I was missing that the jshn parser uses 1-based keys for JSON arrays, instead of 0-based as it is with JavaScript. Now everything is clear to me... I'm going to fix the patch.

**Comment by jow-** [comment]
Merged to master, thanks.

**Pull request closed without merging**
