### PR TITLE
kernel: fq_codel match flows_cnt to limit sizing

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
OpenWRT changed the default fq_codel sch->limit from 10240 to 1024,
without also adjusting q->flows_cnt.  Eric Dumazet explains below that
you must also adjust the buckets (q->flows_cnt) for this not to break.

Eric explains: Limit of 1024 packets and 1024 flows is not wise I think.
(If all buckets are in use, each bucket has a virtual queue of 1 packet,
which is almost the same than having no queue at all)

I suggest to have at least 8 packets per bucket, to let Codel have a
chance to trigger.  So you could either reduce number of buckets to 128
(if memory is tight), or increase limit to 8192.

flows_cnt is now set to 1024/8=128

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by dtaht** [comment]
someone cherry picking this one also will help. https://git.kernel.org/cgit/linux/kernel/git/davem/net-next.git/commit/?id=9d18562a227

**Comment by kdarbyshirebryant** [comment]
Hi Dave,

Well I tried to do the backport to 4.1.23 which is what the LEDE/Openwrt
Archer C7 kernel is on and to be blunt I've struggled and stopped.  It
needs someone who really knows the qdisc api.  I'm surprised at quite
how much things have changed :-)

Apols,

Kevin

**Comment by airend** [comment]
Looks a bit easier on K4.4; I'm testing these now: https://github.com/airend/linux-embedded/compare/lede-p~3...lede-p.

**Comment by kdarbyshirebryant** [comment]
This is my 4.4 backport if it helps https://github.com/kdarbyshirebryant/lede/commit/31226f8b9c9d666594e0aab3e871eed84393e7b9

**Comment by blogic** [comment]
pushed into my staging tree --> https://git.lede-project.org/?p=lede/blogic/staging.git;a=summary

thanks !

**Pull request closed without merging**
