### PR TITLE
[RFC] base-files: Enhancements to /etc/profile

### PR DESCRIPTION
**Pull request by VittGam**
- Change the default prompt to surround the current directory with spaces.
- Add an optional colored prompt, in case the user wants to enable it.
- Update the terminal window title with the current directory and hostname, if using an xterm-compatible terminal emulator.
- Add ll, an useful alias to ls.

This is a preview of the changes done to PS1 (before, after, after + colors):

screenshot_20160505_023509

Cheers,
Vittorio

### CODE REVIEW

**Comment by blogic** [comment]
the changes to PS1 seems very non *nix. i would vote against them, they seem to break expected behaviour

fine with the xterm patch and i can live with the ll one. i know a few people that add the ll thing after installing owrt.

**Comment by VittGam** [comment]
Well, a space surrounded path is used for example as the default PS1 in Arch Linux, or in Gentoo. I find it quite useful when copy-pasting a long path from an xterm, so that I can just double-click on the path in order to select it.

**Comment by blogic** [comment]
i could reply with "debian does not" but i guess that would not benefit the discussion

**Comment by jow-** [comment]
Continued in https://github.com/lede-project/source/pull/4

**Pull request closed without merging**
