### PR TITLE
This patch introduces serial0 aliases in the ramips DTS files

### PR DESCRIPTION
**Pull request by sgalabov**
This patch introduces serial0 aliases in the ramips DTS files, which can
then be used to denote the active console instead of relying on bootargs.

Signed-off-by: Stanislav Galabov <sgalabov@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
thanks, i plan to do more cleanups like this to the ralink device trees.

**Comment by sgalabov** [comment]
let me know what you have in mind, I may be able to help with some of it...

**Comment by blogic** [comment]
dtsi files have full nodes. the dts files should not have the full trelayout but only reference nodes where they make changes via the 

&node_name {
  ...
}

style syntax. i was planning to globally fix this for all ramips dts files and bring them to the format that is expected upstream. if you look in a kernel tree how arm does it, you will quickly see what i mean (arch/arm/boot/dts*)

**Comment by sgalabov** [comment]
I'll see if I can find some time to look at that..

**Comment by blogic** [comment]
cool

**Pull request merged**
